return {
  {
    "williamboman/mason-lspconfig.nvim",
    opts = {
      ensure_installed = {
        "bashls",
        "elixirls",
        "gopls",
        "html",
        "jsonls",
        "kotlin_language_server",
        "lemminx",
        "lua_ls",
        "marksman",
        "rust_analyzer",
        "tailwindcss",
        "yamlls",
      },
    },
    dependencies = {
      { "williamboman/mason.nvim", opts = {} },
      "neovim/nvim-lspconfig",
    },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = {
      ensure_installed = {
        "codelldb",
        "delve",
        "detekt",
        "eslint",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "golines",
        "gomodifytags",
        "gotests",
        "iferr",
        "impl",
        "isort",
        "ktlint",
        "kotlin-debug-adapter",
        "markdownlint",
        "marksman",
        "misspell",
        "prettier",
        "shellcheck",
        "shfmt",
        "stylua",
        "sqlfluff",
        "yamlls",
      },
    },
    dependencies = {
      "williamboman/mason.nvim",
    },
  },
}
